using System;
using System.Reflection;
using UnityEngine;
using RosMessageTypes.Nav;
using RosMessageTypes.Geometry;
partial class Program
{
    static KatHuskyDirectAngleController c; static uint seq; static int count;
    static object Call(string method, params object[] args) => typeof(KatHuskyDirectAngleController).GetMethod(method,BindingFlags.Instance|BindingFlags.NonPublic).Invoke(c,args);
    static bool Active => (bool)typeof(KatHuskyDirectAngleController).GetField("activationEnabled",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(c);
    static void Set(string name,object value)=>typeof(KatHuskyDirectAngleController).GetField(name,BindingFlags.Instance|BindingFlags.NonPublic).SetValue(c,value);
    static void Assert(bool ok,string message){if(!ok)throw new Exception(message);}
    static void Test(string name,Action test){test();Console.WriteLine("PASS "+name);count++;}
    static void Press(KeyCode key){Input.Keys.Add(key);Call("Update");Input.Keys.Clear();Call("Update");}
    static void Tick(float body=0,float robot=0,float speed=0){
        Time.realtimeSinceStartup+=.02f;
        KATNativeSDK.Data=new KATNativeSDK.TreadMillData{connected=true,deviceName="MiniS",extraData=new byte[128],moveSpeed=new Vector3{x=speed},bodyRotationRaw=new Quaternion(0,MathF.Sin(body*Mathf.Deg2Rad/2),0,MathF.Cos(body*Mathf.Deg2Rad/2))};
        seq++;var o=new OdometryMsg();o.header.stamp.sec=100+seq/1000;o.header.stamp.nanosec=(seq%1000)*1000000;
        o.pose.pose.orientation=new QuaternionMsg{z=Math.Sin(robot*Math.PI/360),w=Math.Cos(robot*Math.PI/360)};
        Call("OnOdometry",o);Call("Update");Call("FixedUpdate");
    }
    static void New(){Time.realtimeSinceStartup=10;Time.PhysicsTime=null;seq=0;Input.Keys.Clear();MiniSExtraData.Step=false;c=new KatHuskyDirectAngleController{enableDebugLog=false,enableKeyboardFallback=true,bodyToRosYawSign=1,turnRateDeadZoneDegPerSec=6};Call("OnEnable");Call("Start");Tick();Press(KeyCode.T);Tick();Assert(Active,"start");}
    static void Main(string[] args){
        if(args.Length > 0 && args[0] == "--turn-audit") { RunTurnAudit(); return; }
        if(args.Length > 0 && args[0] == "--export-site") { LabExport.Export(args[1]); return; }
        Test("published turns respect acceleration deceleration and pass through zero on reversal",()=>{New();float previous=c.LastPublishedAngular;bool crossedZero=false;for(int i=0;i<80;i++){float publishedAt=(float)typeof(KatHuskyDirectAngleController).GetField("lastAngularPublishTime",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(c);Time.realtimeSinceStartup+=.02f;Set("lastOdometryTime",Time.realtimeSinceStartup);Call("PublishIfDue",0f,i<40?1.6f:-1.6f);float current=c.LastPublishedAngular;if(current!=previous){float dt=Time.realtimeSinceStartup-publishedAt;float limit=Math.Abs(current)>Math.Abs(previous)?1.5f:3f;Assert(Math.Abs(current-previous)<=limit*dt+.0001f,"published ramp jump");Assert(current*previous>=0,"skipped zero on reversal");}if(i>=40&&current==0)crossedZero=true;previous=current;}Assert(crossedZero&&previous<0,"reversal did not complete");});
        Test("explicit stop and invalid heading bypass ramp immediately",()=>{New();for(int i=0;i<40;i++)Tick(i*2,0);Assert(c.LastPublishedAngular>.5f,"not moving fast before stop");KATNativeSDK.Data.bodyRotationRaw=new Quaternion();Call("FixedUpdate");Assert(c.LastPublishedAngular==0,"heading fault ramped instead of stopping");New();for(int i=0;i<40;i++)Tick(i*2,0);Press(KeyCode.E);Assert(c.LastPublishedAngular==0&&c.LastPublishedLinear==0,"emergency stop delayed");});
        Test("catch-up gain is continuous near slow zone and brakes when approaching",()=>{New();Set("filteredBodyTurnDeg",14.999);float below=(float)Call("CalculateTurn");Set("filteredBodyTurnDeg",15.001);float above=(float)Call("CalculateTurn");Assert(above>=below&&above-below<.001,"gain transition jumped");Set("filteredBodyTurnDeg",90.0);float fast=(float)Call("CalculateTurn");Assert(fast>1f,"large angle not fast");Set("filteredBodyTurnDeg",10.0);float stationary=(float)Call("CalculateTurn");Set("measuredRobotYawRate",20f);float braking=(float)Call("CalculateTurn");Assert(braking>=0&&braking<stationary,"approach did not reduce correction");});
        Test("unstable sensor cannot resume catch-up after recovery grace",()=>{New();Tick(10,0);for(int i=0;i<120;i++){Tick(i%2==0?149:-120,0);Assert(c.LastPublishedAngular==0,"unstable sensor resumed");Assert(Math.Abs(c.BodyTurnDeg-10)<.01,"lost accepted intent");}});
        Test("pulse threshold has no fixed speed boost",()=>{float previous=0;foreach(float input in new[]{.079f,.08f,.081f,.14f}){New();Tick(0,0,input);float actual=c.LastPublishedLinear;float expected=(float)Call("CalculateLinear",input);Assert(Math.Abs(actual-expected)<.00001,"pulse boosted "+input);if(previous>0)Assert(actual>=previous,"non-monotonic response");previous=actual;}});
        Test("held pulse decays without exceeding measured strength and stops promptly",()=>{New();Tick(0,0,.14f);float previous=c.LastPublishedLinear;for(int i=0;i<30;i++){Tick();Assert(c.LastPublishedLinear<=previous+.00001,"tail accelerated");previous=c.LastPublishedLinear;}Assert(previous==0,"tail did not stop within 600ms");});
        Test("captured Mini S range maps progressively instead of saturating at one",()=>{New();float atOne=(float)Call("CalculateLinear",1f);float atThree=(float)Call("CalculateLinear",3f);Assert(atOne>.44f&&atOne<.46f,"one-unit mapping="+atOne);Assert(Math.Abs(atThree-.8f)<.00001,"three-unit max="+atThree);Assert(Math.Abs((float)Call("CalculateLinear",10f)-.8f)<.00001,"above-range input exceeded cap");Assert(Math.Abs((float)Call("CalculateLinear",-3f)+.35f)<.00001,"reverse cap");Assert(Math.Abs((float)Call("CalculateLinear",-10f)+.35f)<.00001,"reverse above-range cap");});
        Test("dead zone boundary starts continuously",()=>{New();Assert((float)Call("CalculateLinear",.02f)==0,"dead zone");Assert((float)Call("CalculateLinear",.02001f)<.002f,"minimum speed jump");float previous=0;for(int i=1;i<=100;i++){float value=(float)Call("CalculateLinear",.02f+i*.001f);Assert(value>=previous,"start ramp not monotonic");previous=value;}});
        Test("pause clears pulse memory before reactivation",()=>{New();Tick(0,0,.5f);Press(KeyCode.T);Press(KeyCode.T);Tick();Assert(c.LastPublishedLinear==0,"stale step survived pause");});
        Test("body 90 deg/s maps to physical-rate feedforward in both directions",()=>{New();foreach(float r in new[]{-180f,-90f,-20f,-6f,0f,6f,20f,90f,180f}){float expected=Math.Sign(r)*Math.Clamp((Math.Abs(r)-6)/84,0,1)*1.5708f;float actual=(float)Call("CalculateOpenLoopTurn",r);Assert(Math.Abs(actual-expected)<.00001,"mapping "+r);}});
        Test("large pending angle has bounded correction without losing target",()=>{foreach(double angle in new[]{-720.0,720.0}){New();Set("filteredBodyTurnDeg",angle);float cmd=(float)Call("CalculateTurn");Assert(Math.Abs(cmd-Math.Sign(angle)*1.2f)<.00001,"correction cap");Assert(c.DesiredRobotYawDeg==angle,"target clipped");}});
        Test("current target determines direction across body rates and error signs",()=>{
            foreach(double error in new[]{-100.0,-27.0,-2.0,0.0,2.0,27.0,100.0})
            foreach(float rate in new[]{-180f,-20f,0f,20f,180f}){
                New();Set("filteredBodyTurnDeg",error);Set("filteredYawRateDegPerSec",rate);
                float cmd=(float)Call("CalculateTurn");
                if(Math.Abs(error)<=2)Assert(cmd==0,"turn while target aligned");
                else {Assert(cmd*error>0,"rate overrode target direction");if(rate*error<0)Assert(c.LiveTurnDemand==0&&c.CorrectionTurnDemand*error>0,"return motion cancelled catch-up");}
            }
        });
        Test("90 to 87 degree return keeps chasing then reverses only beyond robot",()=>{
            foreach(float sign in new[]{-1f,1f}){
                New();c.bodyYawFilterTime=0;c.turnRateSmoothingTime=0;
                for(int i=1;i<=90;i++)Tick(sign*i,sign*Math.Min(i,60));
                for(int i=89;i>=87;i--){Tick(sign*i,sign*60);Assert(Math.Abs(c.TargetTurnDeg-sign*i)<.01,"target did not follow return");Assert((float)Call("CalculateTurn")*sign>0&&c.LastPublishedAngular*sign>=0,"return reversed before crossing robot");}
                for(int i=86;i>=50;i--){Tick(sign*i,sign*60);float cmd=(float)Call("CalculateTurn");Assert(cmd*c.HeadingErrorDeg>=0,"command points away from updated target");}
                for(int i=0;i<50;i++)Tick(sign*50,sign*60);
                Assert(c.LastPublishedAngular*sign<0,"did not reverse after target crossed robot");
            }
        });
        Test("logged return at 64 seconds retains positive catch-up",()=>{New();Set("filteredBodyTurnDeg",64.1);Set("filteredYawRateDegPerSec",-12.4f);Set("measuredRobotYawRate",25.2f);float cmd=(float)Call("CalculateTurn");Assert(cmd>0&&c.LiveTurnDemand==0&&c.CorrectionTurnDemand>0,"logged return caused reverse");});
        Test("predictive braking never lets returning body rate reverse chase",()=>{foreach(float sign in new[]{-1f,1f}){New();Set("filteredBodyTurnDeg",(double)sign*5);Set("filteredYawRateDegPerSec",-sign*90);Set("measuredRobotYawRate",sign*30);Assert((float)Call("CalculateTurn")==0,"opposing rate leaked when feedback was zero");Assert(c.TurnStatus=="BRAKING TOWARD TARGET","braking incorrectly labelled aligned");}});
        Test("two-degree gait sway with delayed yaw feedback stays small",()=>{New();float robot=0,peak=0;var history=new System.Collections.Generic.Queue<float>();for(int i=0;i<15;i++)history.Enqueue(0);for(int i=1;i<=1000;i++){float t=i*.02f;float body=i<=600?2*MathF.Sin(2*MathF.PI*t):0;float measured=history.Dequeue();Tick(body,measured,i<=600&&i%4==1?.1f:0);peak=Math.Max(peak,Math.Abs(c.LastPublishedAngular));robot+=c.LastPublishedAngular*.65f*.02f*Mathf.Rad2Deg;history.Enqueue(robot);}Assert(peak<.12,"gait command="+peak);Assert(Math.Abs(robot)<2.5,"gait final yaw="+robot);Console.WriteLine("  sway peak="+peak.ToString("F3")+", final yaw="+robot.ToString("F2"));});
        Test("30-degree turn settles with 300ms feedback delay and chassis response lag",()=>{foreach(float sign in new[]{1f,-1f}){New();float robot=0,velocity=0,peakYaw=0;var history=new System.Collections.Generic.Queue<float>();for(int i=0;i<15;i++)history.Enqueue(0);for(int i=1;i<=2500;i++){Tick(sign*Math.Min(i*.6f,30),history.Dequeue());velocity+=(c.LastPublishedAngular*.65f-velocity)*(1-MathF.Exp(-.02f/.25f));robot+=velocity*.02f*Mathf.Rad2Deg;history.Enqueue(robot);peakYaw=Math.Max(peakYaw,sign*robot);}Assert(Math.Abs(robot-sign*30)<2.1,"delayed final yaw="+robot);Assert(peakYaw<33,"delayed overshoot="+peakYaw);Console.WriteLine("  delayed turn final="+robot.ToString("F2")+", peak="+peakYaw.ToString("F2"));}});
        Test("step pulse gaps keep forward output during fast turns in either direction",()=>{foreach(float sign in new[]{1f,-1f}){New();for(int i=1;i<=40;i++){Tick(sign*i*3,0,i%4==1?.1f:0f);Assert(c.LastPublishedLinear>0,"turn suppressed held footstep at tick "+i);if(i>5)Assert(sign*c.LastPublishedAngular>0,"turn lost");}for(int i=0;i<30;i++)Tick(sign*120,0);Assert(c.LastPublishedLinear==0,"step hold failed to expire");}});
        Test("device step signal drives forward while body turns even with zero raw speed",()=>{New();MiniSExtraData.Step=true;for(int i=1;i<=30;i++){Tick(i*3,0);Assert(c.LastPublishedLinear>0,"device step suppressed");}MiniSExtraData.Step=false;for(int i=0;i<15;i++)Tick(90,0);Assert(c.LastPublishedLinear==0,"device stop");});
        Test("body turn alone does not synthesize forward movement",()=>{New();for(int i=1;i<=30;i++){Tick(i*3,0);Assert(c.LastPublishedLinear==0,"turn created forward");}Assert(c.LastPublishedAngular>0,"body-only turn lost");});
        Test("straight stepping with stable body heading does not create turning",()=>{New();for(int i=1;i<=60;i++){Tick(0,0,i%4==1?.1f:0f);Assert(c.LastPublishedLinear>0,"straight pulse lost");Assert(c.LastPublishedAngular==0,"step created turn");}});
        Test("one press persists through repeated walking and stops",()=>{New();for(int n=0;n<5;n++){Tick(0,0,.5f);Assert(c.LastPublishedLinear>0,"walk missing");for(int i=0;i<35;i++)Tick();Assert(Active,"idle cancelled activation");Assert(c.LastPublishedLinear==0,"idle motion");}Press(KeyCode.T);Assert(!Active&&c.LastPublishedLinear==0&&c.LastPublishedAngular==0,"pause");});
        Test("trigger threshold noise and short false releases do not create another edge",()=>{New();Assert((bool)Call("UpdateTriggerState",.3f),"first press");foreach(float v in new[]{.19f,.21f,.12f,.22f,0f,.25f}){Time.realtimeSinceStartup+=.02f;Assert((bool)Call("UpdateTriggerState",v),"spurious release");}Call("UpdateTriggerState",0f);Time.realtimeSinceStartup+=.1f;Assert(!(bool)Call("UpdateTriggerState",0f),"release");Assert((bool)Call("UpdateTriggerState",.3f),"second press");});
        Test("single KAT dropout stops commands and resumes without trigger",()=>{New();Tick(10,0,.5f);KATNativeSDK.Data.connected=false;Call("FixedUpdate");Assert(c.LastPublishedLinear==0&&c.LastPublishedAngular==0,"fault stop");Assert(Active,"short dropout disarmed");Tick(10,0,.5f);Assert(Active&&c.LastPublishedLinear>0,"resume");Assert(c.HeadingErrorDeg>0,"short fault lost pending turn");});
        Test("invalid walking sample has same short recovery",()=>{New();KATNativeSDK.Data.moveSpeed=new Vector3{x=float.NaN};Call("FixedUpdate");Assert(Active&&c.LastPublishedLinear==0,"invalid input");Tick(0,0,.3f);Assert(c.LastPublishedLinear>0,"resume");});
        Test("long disconnect requires explicit restart",()=>{New();KATNativeSDK.Data.connected=false;Call("FixedUpdate");Time.realtimeSinceStartup+=1.2f;Call("FixedUpdate");Tick(0,0,.5f);Assert(!Active&&c.LastPublishedLinear==0,"long fault auto resumed");Press(KeyCode.T);Tick(0,0,.5f);Assert(Active&&c.LastPublishedLinear>0,"restart");});
        Test("long gap detected even without intermediate ticks",()=>{New();KATNativeSDK.Data.connected=false;Call("FixedUpdate");Time.realtimeSinceStartup+=1.2f;Tick(0,0,.5f);Assert(!Active&&c.LastPublishedLinear==0,"stalled recovery");});
        Test("manual pause during short fault remains paused",()=>{New();KATNativeSDK.Data.connected=false;Call("FixedUpdate");Press(KeyCode.T);Tick(0,0,.5f);Assert(!Active&&c.LastPublishedLinear==0,"pause lost");});
        Test("software stop and release do not restart",()=>{New();Press(KeyCode.E);Tick(20,0,.5f);Press(KeyCode.E);Tick(20,0,.5f);Assert(!Active&&c.LastPublishedLinear==0&&c.LastPublishedAngular==0,"stop lost");});
        Test("one-degree quantization impulse stays below 0.2 rad/s",()=>{New();float peak=0;for(int i=0;i<40;i++){Tick(1,0);peak=Math.Max(peak,Math.Abs(c.LastPublishedAngular));}Assert(peak<.2f,"peak="+peak);Console.WriteLine("  one-degree peak="+peak.ToString("F3"));});
        Test("small error is not forced to minimum command",()=>{New();for(int i=0;i<70;i++)Tick(6,0);Assert(c.LastPublishedAngular>0&&c.LastPublishedAngular<.12f,"floor or scale still active");});
        Test("both full-turn directions converge within 120 seconds with bounded correction",()=>{foreach(float sign in new[]{1f,-1f}){New();float robot=0;for(int i=1;i<=6000;i++){Tick(sign*Math.Min(i*1.8f,360),robot);Assert(Active&&c.HeadingCalibrated,"lost activation");Assert(Math.Abs(c.LastPublishedAngular)<=1.6001f,"cap");robot+=c.LastPublishedAngular*.02f*Mathf.Rad2Deg*.65f;}Assert(Math.Abs(robot-sign*360)<2.1,"angle="+robot);}});
        Test("invalid body sample stops turn but preserves pending angle",()=>{New();Set("bodyTurnDeg",90.0);Set("filteredBodyTurnDeg",90.0);Tick(0,0);KATNativeSDK.Data.bodyRotationRaw=new Quaternion();Call("FixedUpdate");Assert(c.LastPublishedAngular==0&&c.HeadingCalibrated,"suspend");Tick(0,0);Assert(Math.Abs(c.HeadingErrorDeg-90)<.01&&c.LastPublishedAngular>0,"target lost");});
        Test("invalid odometry packet retains baseline and real robot progress",()=>{New();Tick(0,30);Set("robotReference",0.0);Set("bodyTurnDeg",90.0);Set("filteredBodyTurnDeg",90.0);Call("OnOdometry",new object[]{null});Assert(!c.HasFreshOdometry&&c.HeadingCalibrated,"invalid odometry suspend");Tick(0,40);Assert(Math.Abs(c.HeadingErrorDeg-50)<.01,"progress discarded");});
        Test("short stale odometry gap counts motion instead of shifting target",()=>{New();Tick(0,30);Set("robotReference",0.0);Set("bodyTurnDeg",90.0);Set("filteredBodyTurnDeg",90.0);Time.realtimeSinceStartup+=.6f;Tick(0,40);Assert(Math.Abs(c.HeadingErrorDeg-50)<.01,"gap added false target");});
        Test("odometry unwrap keeps positive and negative full turns",()=>{foreach(float sign in new[]{1f,-1f}){New();for(int i=1;i<=240;i++)Tick(sign*i*3,sign*i*3);Assert(Math.Abs(c.RobotTurnDeg-sign*720)<.02,"odom lost revolution");}});
        Test("long odometry gap discards old target",()=>{New();Set("bodyTurnDeg",90.0);Set("filteredBodyTurnDeg",90.0);Time.realtimeSinceStartup+=1.2f;Tick(0,40);Assert(Math.Abs(c.HeadingErrorDeg)<.01,"long gap target");});
        Test("frame reset shifts reference and resets progress watcher",()=>{New();Set("bodyTurnDeg",90.0);Set("filteredBodyTurnDeg",90.0);Set("watchingTurnProgress",true);var o=new OdometryMsg();o.header.stamp.sec=200;o.header.frame_id="new_odom";o.pose.pose.orientation=new QuaternionMsg{z=Math.Sin(-100*Math.PI/360),w=Math.Cos(-100*Math.PI/360)};Call("OnOdometry",o);Assert(Math.Abs(c.HeadingErrorDeg-90)<.01,"frame reset lost error");Assert(!(bool)typeof(KatHuskyDirectAngleController).GetField("watchingTurnProgress",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(c),"progress baseline not reset");});
        Test("body glitch suspends old feedforward and keeps accepted time",()=>{New();Tick(10,0);Time.realtimeSinceStartup+=.02f;Call("UpdateTurnRate",149f);Assert((float)Call("CalculateTurn")==0,"stale feedforward");Time.realtimeSinceStartup+=.02f;Call("UpdateTurnRate",12f);Assert(Math.Abs(c.BodyTurnDeg-12)<.01,"bad baseline");Assert((float)Call("CalculateTurn")>0,"did not recover");});
        Test("persistent body jump rebases sensor without cancelling accepted turn",()=>{New();Tick(10,0);for(int i=0;i<90;i++){Tick(149,0);Assert(Math.Abs(c.BodyTurnDeg-10)<.01,"glitch leaked or target dropped");}Assert(c.LastPublishedAngular>0,"did not resume catch-up");Tick(151,0);Assert(Math.Abs(c.BodyTurnDeg-12)<.01,"new sensor baseline incorrect");});
        Test("wall clock handles a hitch independently of physics time",()=>{New();c.bodyYawFilterTime=0;c.turnRateSmoothingTime=0;Time.PhysicsTime=10.02f;Time.realtimeSinceStartup+=.2f;Call("UpdateTurnRate",60f);Assert(Math.Abs(c.BodyTurnDeg-60)<.01,"hitch rejected legitimate angle");Assert(Math.Abs(c.FilteredYawRateDegPerSec-300)<1,"wrong sampling clock");double target=c.TargetTurnDeg;Call("UpdateTurnRate",60f);Assert(c.TargetTurnDeg==target&&Math.Abs(c.FilteredYawRateDegPerSec-300)<1,"catch-up tick advanced filter");Time.PhysicsTime=null;});
        Test("blocked chassis drops unreachable pending turn",()=>{New();Set("bodyTurnDeg",90.0);Set("filteredBodyTurnDeg",90.0);for(int i=0;i<300;i++)Tick(0,0);Assert(Math.Abs(c.HeadingErrorDeg)<.01&&c.LastPublishedAngular==0,"blocked target persists");});
        Console.WriteLine(count+" tests passed (simulated, no robot connection).");
    }
}
